services:
  db:
    image: postgres:15-alpine
    container_name: blood-vault-db
    restart: always
    environment:
      POSTGRES_USER: blood_user
      POSTGRES_PASSWORD: blood_password
      POSTGRES_DB: blood_vault
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: